pub fn dispatch(cli: Cli) -> Result<()> {
    match cli.command {
        Commands::Setup {
            yes,
            project,
            source,
            vault,
            key_mode,
            commit_vault,
            ignore_vault,
            remove_plaintext,
            keep_plaintext,
            unlock_ttl,
            no_unlock,
            workspace,
            apps,
            all,
        } => {
            let options = SetupOptions {
                yes,
                project,
                source,
                vault,
                key_mode: key_mode.into(),
                commit_vault,
                ignore_vault,
                remove_plaintext,
                keep_plaintext,
                unlock_ttl,
                no_unlock,
            };
            if workspace {
                setup_workspace(options, apps, all)
            } else {
                setup(options)
            }
        }
        Commands::Init {
            project,
            force,
            bare,
        } => init(project, force, bare),
        Commands::Import {
            source,
            vault,
            key_mode,
        } => import(source, vault, key_mode.into()),
        Commands::Register {
            project,
            path,
            vault,
        } => register(project, path, vault),
        Commands::Use { project } => use_project(&project),
        Commands::Projects { command } => projects_command(command),
        Commands::Config { command } => config_command(command),
        Commands::Store { command } => store_command(command),
        Commands::Env { command } => env_command(command),
        Commands::Request {
            project,
            app,
            profile,
            agent,
            agent_key_id,
            worktree,
            git_remote,
            commit,
            branch,
            action,
            command,
            env_names,
            json,
            no_prompt,
        } => request_for_target(RequestTargetOptions {
            project,
            app,
            profile,
            context: AgentContextOptions {
                agent,
                agent_key_id,
                worktree,
                git_remote,
                commit,
                branch,
            },
            action,
            command,
            env_names,
            json,
            no_prompt,
        }),
        Commands::Allow {
            project,
            app,
            profile,
            scope,
            agent,
            branch,
            command,
            env_names,
        } => allow_for_target(AllowTargetOptions {
            project,
            app,
            profile,
            scope,
            agent,
            branch,
            command,
            env_names,
        }),
        Commands::Grants { command } => grants_command(command),
        Commands::Approvals { command } => approvals_command(command),
        Commands::Approve {
            request_id,
            scope,
            confirm_critical,
            agent_mediated,
            json,
        } => approve(request_id, scope, confirm_critical, agent_mediated, json),
        Commands::Deny {
            request_id,
            agent_mediated,
            json,
        } => deny(request_id, agent_mediated, json),
        Commands::Run {
            profile,
            project,
            app,
            agent,
            agent_key_id,
            worktree,
            git_remote,
            commit,
            branch,
            action,
            env_names,
            json,
            no_prompt,
            wait_for_approval,
            approval_timeout,
            command,
        } => run_with_context(
            RunOptions {
                profile,
                project,
                agent: agent.clone(),
                branch: branch.clone(),
                action,
                env_names,
                command,
                json,
                no_prompt,
                wait_for_approval,
                approval_timeout,
            },
            AgentContextOptions {
                agent,
                agent_key_id,
                worktree,
                git_remote,
                commit,
                branch,
            },
            app,
        ),
        Commands::Dev {
            project,
            app,
            agent,
            agent_key_id,
            worktree,
            git_remote,
            commit,
            branch,
            json,
            no_prompt,
        } => run_with_context(
            RunOptions {
                profile: Some("dev".to_string()),
                project,
                agent: agent.clone(),
                branch: branch.clone(),
                action: None,
                env_names: Vec::new(),
                command: Vec::new(),
                json,
                no_prompt,
                wait_for_approval: false,
                approval_timeout: "30m".to_string(),
            },
            AgentContextOptions {
                agent,
                agent_key_id,
                worktree,
                git_remote,
                commit,
                branch,
            },
            app,
        ),
        Commands::Migrate {
            project,
            app,
            agent,
            agent_key_id,
            worktree,
            git_remote,
            commit,
            branch,
            json,
            no_prompt,
        } => run_with_context(
            RunOptions {
                profile: Some("migrate".to_string()),
                project,
                agent: agent.clone(),
                branch: branch.clone(),
                action: None,
                env_names: Vec::new(),
                command: Vec::new(),
                json,
                no_prompt,
                wait_for_approval: false,
                approval_timeout: "30m".to_string(),
            },
            AgentContextOptions {
                agent,
                agent_key_id,
                worktree,
                git_remote,
                commit,
                branch,
            },
            app,
        ),
        Commands::Doctor { project, app, all } => doctor_for_target(project, app, all),
        Commands::Broker { command } => broker_command(command),
        Commands::Worktrees { command } => worktrees_command(command),
        Commands::Workspace { command } => workspace_command(command),
        Commands::Logs { command, kind } => logs(command, kind),
        Commands::Edit { project, app } => edit(project, app),
        Commands::Unlock {
            project,
            app,
            all,
            ttl,
            mode,
            verify_only,
        } => unlock_vault_for_target(project, app, all, &ttl, mode.as_deref(), verify_only),
        Commands::Modes { command } => modes_command(command),
        Commands::Lock {
            project,
            app,
            workspace,
            all,
        } => lock(project, app, workspace, all),
        Commands::Off {
            discover,
            each,
            json,
        } => ward_off(discover, each, json),
        Commands::On { each, json } => ward_on(each, json),
        Commands::Teardown {
            project,
            app,
            export_path,
            yes,
            restore_env,
        } => teardown(project, app, export_path, yes, restore_env),
        #[cfg(all(coverage, not(test)))]
        Commands::Coverage => coverage_exercise_cli_edges(),
        Commands::BrokerServe => broker::serve(),
        Commands::ShellInit { shell } => shell_init(shell.as_deref()),
        Commands::Rotate { project, app } => rotate_vault(project, app),
        Commands::Key {
            project,
            app,
            command,
        } => key_command(project, app, command),
        Commands::Recovery {
            project,
            app,
            command,
        } => recovery_command(project, app, command),
        Commands::Dashboard { command } => dashboard_command(command),
        Commands::DashboardServer { port, token } => crate::webui::serve_standalone(port, token),
        Commands::Human {
            project,
            app,
            all,
            ttl,
        } => crate::human::activate_human_mode(project, app, all, &ttl),
        Commands::HumanGuardian {
            shell_pid,
            session_token,
            ttl_seconds,
            projects,
        } => crate::human::serve_guardian(shell_pid, &session_token, ttl_seconds, projects),
    }
}
